#ifndef GUARD_CONSTANTS_SEASONS_H
#define GUARD_CONSTANTS_SEASONS_H

#define SEASON_SUMMER 0
#define SEASON_FALL 1
#define SEASON_WINTER 2
#define SEASON_SPRING 3

#endif  // GUARD_CONSTANTS_SEASONS_H